batch_size: 128
epochs: 30
lr: 0.0001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

# data_dir: data
data_dir: /content/drive/MyDrive/Colab Notebooks/DLBasics2024_colab/final/dl_lecture_competition_pub/data

# Evaluation
model_path:
